// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZvQ7HGDGwZeEbzwuaqehT80UxLLkinsE',
    appId: '1:946784222951:web:bf178830e38ddb94982c42',
    messagingSenderId: '946784222951',
    projectId: 'nimmadhi-4c375',
    authDomain: 'nimmadhi-4c375.firebaseapp.com',
    storageBucket: 'nimmadhi-4c375.appspot.com',
    measurementId: 'G-9JH4F6EZK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIe3Oqv93rYtsOtiuhUmuCpQKiCqXXGCo',
    appId: '1:946784222951:android:5efc4e01320f0412982c42',
    messagingSenderId: '946784222951',
    projectId: 'nimmadhi-4c375',
    storageBucket: 'nimmadhi-4c375.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_2uQ9_PthKLxJYuwIjPBQ9Z13TdT8Jhk',
    appId: '1:946784222951:ios:a82a2d111e390e67982c42',
    messagingSenderId: '946784222951',
    projectId: 'nimmadhi-4c375',
    storageBucket: 'nimmadhi-4c375.appspot.com',
    androidClientId: '946784222951-kafv3h5k60r7pnaniv8rovucoeu9ausc.apps.googleusercontent.com',
    iosClientId: '946784222951-njn9ktj7uh86hptg6fhmttrcm77p1vkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.agni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_2uQ9_PthKLxJYuwIjPBQ9Z13TdT8Jhk',
    appId: '1:946784222951:ios:a82a2d111e390e67982c42',
    messagingSenderId: '946784222951',
    projectId: 'nimmadhi-4c375',
    storageBucket: 'nimmadhi-4c375.appspot.com',
    androidClientId: '946784222951-kafv3h5k60r7pnaniv8rovucoeu9ausc.apps.googleusercontent.com',
    iosClientId: '946784222951-njn9ktj7uh86hptg6fhmttrcm77p1vkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.agni',
  );
}
